export enum ErrorCode {
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    EXPIRED_TOKEN = "EXPIRED_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIAL",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    INTERNAL_ERROR = "INTERNAL_ERROR",
}