export enum AuthErrorCode {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    INVALID_TOKEN = 'INVALID_TOKEN',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    UNKNOWN = 'UNKNOWN',
}
