export enum ControllerErrorCode {
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    NO_SUCH_USER = "NO_SUCH_USER",
    TOKEN_EXPIRED = "EXPIRED_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIAL",
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST",
    INTERNAL_ERROR = "INTERNAL_ERROR",


    /**JWT ERRORS */
    


 

}