export enum ControllerErrorCode {
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    EXPIRED_TOKEN = "EXPIRED_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIAL",
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    

 

}