import { DBInfo } from '../db-info';

/**
 * Request interface for adding a new database connection.
 *
 * Contains database information without UID (which will be generated by the server).
 *
 * @category Requests
 * @since 1.0.0
 */
export type AddDbRequest = Omit<DBInfo, 'uid'>;
