export enum DatabaseErrorCode {
    GET_START_INFO_FAILED = 'GET_START_INFO_FAILED',
    START_DATABASE_FAILED = 'START_DATABASE_FAILED',
    STOP_DATABASE_FAILED = 'STOP_DATABASE_FAILED',
    RESTART_DATABASE_FAILED = 'RESTART_DATABASE_FAILED',
    LOGIN_DATABASE_FAILED = 'LOGIN_DATABASE_FAILED',
    MISSING_DB_CREDENTIALS = 'MISSING_DB_CREDENTIALS',
    HOST_NOT_FOUND = 'HOST_NOT_FOUND',
    HOST_ERROR = 'HOST_ERROR',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    DUPLICATED_DATABASE_PROFILE = 'DUPLICATED_DATABASE_PROFILE',
}

