export enum DatabaseErrorCode {
    GET_START_INFO_FAILED = 'GET_START_INFO_FAILED',
    START_DATABASE_FAILED = 'START_DATABASE_FAILED',
    STOP_DATABASE_FAILED = 'STOP_DATABASE_FAILED',
    RESTART_DATABASE_FAILED = 'RESTART_DATABASE_FAILED',
}

